# Generated by Django 5.2 on 2025-04-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDaRodada', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slogan', models.CharField(max_length=250)),
                ('anoFundacao', models.PositiveIntegerField()),
                ('pontos', models.IntegerField(default=70)),
            ],
        ),
        migrations.CreateModel(
            name='Batalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.rodada')),
                ('primeiraStartup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primeiraStarBatalhas', to='torneio.startup')),
                ('segundaStartup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundaStarBatalhas', to='torneio.startup')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batalhasVencidas', to='torneio.startup')),
            ],
        ),
        migrations.AddField(
            model_name='rodada',
            name='startups',
            field=models.ManyToManyField(to='torneio.startup'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PITCH', 'Pitch convincente'), ('BUGS', 'Produto com bugs'), ('TRACAO', 'Boa tração de usuários'), ('INVESTIRRITADO', 'Investidor irritado'), ('FAKENEWS', 'Fake news no pitch')], max_length=15)),
                ('batalha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.batalha')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.startup')),
            ],
        ),
    ]
