# Generated by Django 5.2 on 2025-04-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('data_final', models.DateTimeField(auto_now_add=True)),
                ('campea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.startup')),
            ],
        ),
        migrations.CreateModel(
            name='TorneioEstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField()),
                ('pitches', models.PositiveIntegerField()),
                ('bugs', models.PositiveIntegerField()),
                ('tracoes', models.PositiveIntegerField()),
                ('investidores', models.PositiveIntegerField()),
                ('penalidades', models.PositiveIntegerField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.startup')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='torneio.torneio')),
            ],
            options={
                'unique_together': {('torneio', 'startup')},
            },
        ),
    ]
