# Generated by Django 5.2 on 2025-04-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0002_torneio_torneioestat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TorneioEstat',
            new_name='TorneioStats',
        ),
    ]
