# Generated by Django 5.2 on 2025-04-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0003_rename_torneioestat_torneiostats'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='statsJaSalvos',
            field=models.BooleanField(default=False),
        ),
    ]
