# Generated by Django 5.2 on 2025-04-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0004_torneio_statsjasalvos'),
    ]

    operations = [
        migrations.AddField(
            model_name='batalha',
            name='shark_fight',
            field=models.BooleanField(default=False),
        ),
    ]
